spring:
    datasource:
        url: jdbc:postgresql://43.200.52.223:5432/postgres
        username: postgres
        password: h98016995!
        driver-class-name: org.postgresql.Driver
    server:
        port: 8080
        
    web:
        resources:
            static-locations: file:///C:/uploads/

file:
    upload-dir: C:/uploads/  # 개발 환경에서 사용할 저장 경로

cors:
    allowed-origins: "http://localhost:3000,http://localhost:8081,http://192.168.219.113:8081"
