spring:
    application:
        name: baskettime
    
    datasource:
        url: jdbc:postgresql://192.168.56.101:5432/postgres
        username: postgres
        password: h98016995!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    mvc:
        static-path-pattern: /**
    
    task:
        scheduling:
            enabled: "true"
    jackson:
        default-property-inclusion: non-null
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 94369390250-qhr7ger2mipm39827emlfdsqacce3egc.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email
                        redirect-uri: "{baseUrl}/login/oauth2/google"
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

logging: 
    level: 
        root: INFO