spring:
    profiles:
        active: prod
        
    application:
        name: baskettime

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                id:
                    new_generator_mappings: true

    mvc:
        static-path-pattern: /**
    
    task:
        scheduling:
            enabled: true
    jackson:
        default-property-inclusion: non-null
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
        
logging: 
    level: 
        root: INFO
        org:    
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
            springframework:
                web:
                    client:
                        RestTemplate: INFO
