spring:
    application:
        name: baskettime
    
    datasource:
        url: jdbc:postgresql://192.168.56.101:5432/postgres
        username: postgres
        password: h98016995!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    mvc:
        static-path-pattern: /**
    
    task:
        scheduling:
            enabled: "true"