spring:
    application:
        name: baskettime
    web:
        resources:
            static-locations: file:///C:/uploads/

    datasource:
        url: jdbc:postgresql://43.200.52.223:5432/postgres
        username: postgres
        password: h98016995!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                id:
                    new_generator_mappings: true

    mvc:
        static-path-pattern: /**
    
    task:
        scheduling:
            enabled: true
    jackson:
        default-property-inclusion: non-null
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 94369390250-qhr7ger2mipm39827emlfdsqacce3egc.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email
                        redirect-uri: "http://localhost:8080/api/auth/google/callback"
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

logging: 
    level: 
        root: INFO
        org:    
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE