spring:
    profiles:
        active: dev
        
    application:
        name: baskettime

    websocket:
        enabled: true

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                id:
                    new_generator_mappings: true

    mvc:
        static-path-pattern: /**
        dispatch:
            option-request: true
        servlet:
            encoding:
                charset: UTF-8
                enabled: true
                force: true
    message:
        basename: messages
        encoding: UTF-8

    task:
        scheduling:
            enabled: true
    jackson:
        default-property-inclusion: non-null
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        date-format: yyyy-MM-dd'T'HH:mm:ss
        time-zone: Asia/Seoul
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
        
logging: 
    level: 
        root: INFO
        org:    
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
            springframework:
                web:
                    client:
                        RestTemplate: INFO

server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
push:
    expo:
        url: "https://exp.host/--/api/v2/push/send"
    fcm:
        url: "https://fcm.googleapis.com/fcm/send"